# Generated by Django 6.0.5 on 2026-06-27 04:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_passwordresetotp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordresetotp',
            options={'verbose_name': 'Password Reset OTP', 'verbose_name_plural': 'Password Reset OTPs'},
        ),
        migrations.AlterModelOptions(
            name='quizquestion',
            options={'verbose_name': 'Quiz Question', 'verbose_name_plural': 'Quiz Questions'},
        ),
        migrations.AlterModelOptions(
            name='scanlog',
            options={'ordering': ['-created_at'], 'verbose_name': 'Scan Log', 'verbose_name_plural': 'Scan Logs'},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Subscriber', 'verbose_name_plural': 'Subscribers'},
        ),
        migrations.CreateModel(
            name='UserIntegration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_client_id', models.CharField(blank=True, default='', max_length=255)),
                ('gmail_access_token', models.TextField(blank=True, default='')),
                ('twilio_sid', models.CharField(blank=True, default='', max_length=100)),
                ('twilio_token', models.CharField(blank=True, default='', max_length=100)),
                ('twilio_from', models.CharField(blank=True, default='', max_length=20)),
                ('twilio_to', models.CharField(blank=True, default='', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='integration_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Integration Config',
                'verbose_name_plural': 'User Integration Configs',
            },
        ),
    ]
