# Generated by Django 6.0.5 on 2026-06-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_passwordresetotp_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanlog',
            name='sender',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='scanlog',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
