# Generated by Django 6.0.5 on 2026-07-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_blogpost_faq_subscriptionplan_teammember_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('industry', models.CharField(max_length=100)),
                ('logo', models.CharField(blank=True, max_length=50)),
                ('challenge', models.TextField()),
                ('solution', models.TextField()),
                ('results', models.JSONField(default=list)),
                ('testimonial', models.JSONField(default=dict)),
                ('timeline', models.CharField(max_length=100)),
                ('technologies', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('job_type', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('responsibilities', models.JSONField(default=list)),
                ('requirements', models.JSONField(default=list)),
                ('salary', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
