# Generated by Django 6.0.5 on 2026-07-09 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_contactlead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Email', 'Email'), ('Cloud Storage', 'Cloud Storage'), ('Identity Providers', 'Identity Providers'), ('Productivity', 'Productivity')], max_length=50)),
                ('description', models.TextField(blank=True, default='')),
                ('client_id', models.CharField(blank=True, default='', max_length=255)),
                ('client_secret', models.CharField(blank=True, default='', max_length=255)),
                ('redirect_uri', models.CharField(blank=True, default='', max_length=255)),
                ('auth_url', models.CharField(blank=True, default='', max_length=255)),
                ('token_url', models.CharField(blank=True, default='', max_length=255)),
                ('default_scopes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectedAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_account_id', models.CharField(blank=True, default='', max_length=255)),
                ('provider_account_email', models.CharField(blank=True, default='', max_length=255)),
                ('access_token', models.TextField(blank=True, default='')),
                ('refresh_token', models.TextField(blank=True, default='')),
                ('scopes_granted', models.TextField(blank=True, default='')),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('connected', 'Connected'), ('failed', 'Failed'), ('pending', 'Pending Authorization'), ('disconnected', 'Disconnected')], default='pending', max_length=20)),
                ('health_status', models.CharField(default='Healthy', max_length=20)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connected_accounts', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.oauthprovider')),
            ],
            options={
                'unique_together': {('user', 'provider', 'provider_account_id')},
            },
        ),
        migrations.CreateModel(
            name='IntegrationSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('success', 'Success'), ('error', 'Error')], max_length=20)),
                ('items_synced', models.IntegerField(default=0)),
                ('threats_detected', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('duration_ms', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('connected_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='api.connectedaccount')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
