# Generated by Django 6.0.5 on 2026-07-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_adminauthkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='userintegration',
            name='openai_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='userintegration',
            name='virustotal_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
